### ISSUE TITLE
CM Refactoring(Builder Pattern)

### ISSUE THREAD

**Issue by larvinion** [kosslab-kr/cubrid-manager#31]
Trigger Class에 Builder Pattern을 적용하여 Refactoring 진행

- 경로
com.cubrid.common.core/src/com/cubrid/common/core/common/model/Trigger.java
com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/trigger/action/NewTriggerAction.java
com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/trigger/dialog/CreateTriggerDialog.java
com.cubrid.cubridmanager.core.testfragment/src/com/cubrid/cubridmanager/core/cubrid/database/model/DatabaseInfoTest.java
com.cubrid.cubridmanager.core.testfragment/src/com/cubrid/cubridmanager/core/cubrid/trigger/model/TriggerDDLTest.java
com.cubrid.cubridmanager.core.testfragment/src/com/cubrid/cubridmanager/core/cubrid/trigger/model/TriggerTest.java
com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/cubrid/trigger/task/JDBCGetTriggerInfoTask.java
com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/cubrid/trigger/task/JDBCGetTriggerListTask.java
com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/utils/ModelUtil.java

- 사유
Refactoring Builder Pattern 적용
Trigger Class 내 setDescription(String description) 존재 -> AlterTriggerAction.java 에서 setDescription 직접 호출(차후 수정 예정)

**Comment by hornetmj** [comment]
검토 진행 중 입니다.

**Comment by hornetmj** [comment]
merge 되었습니다. 확인하신 후 이슈 종료해주세요.
