### ISSUE TITLE
CM Refactoring(MVC pattern)

### ISSUE THREAD

**Issue by gayeonkim1559** [kosslab-kr/cubrid-manager#33]
Refactoring the HostNavigator View related codes using MVC Pattern

* Route
  com.cubrid.cubridmanager.ui.common.navigator.CubridHostNavigatorView 
  com.cubrid.cubridmanager.ui.spi.action.CubridMenuProvider
  com.cubrid.common.ui.spi.action.ActionManager

* Current
Now, building popup-menu is conducted in not only CubridHostNavigatorView but also CubridMenuProvider especially in the case of a server selection.

**Comment by hornetmj** [comment]
어떤 문제를 해결하려고 한 것인지 상세히 기술해 주시길 바랍니다.
