### ISSUE TITLE
Entitys 오타 수정

### ISSUE THREAD

**Issue by estanie** [kosslab-kr/cubrid-manager#44]
아래 경로에 정의된 Entitys 명을 Entities 로 수정

- 경로
/com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/database/erwin/ERXmlContainer.java

- 사유
오타

**Comment by hornetmj** [comment]
코드 merge 되었습니다.

확인하신 후 이슈 종료해주세요.
