### ISSUE TITLE
CM Convert to CamelCase

### ISSUE THREAD

**Issue by larvinion** [kosslab-kr/cubrid-manager#48]
Cubrid Manager 내 기존 코드에 대한 CamelCase 변환

- 변수명, 메소드(함수)명

**Comment by larvinion** [comment]
#32 PullRequest

- 경로
com.cubrid.common.core/src/com/cubrid/common/core/common/model/Trigger.java
com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/trigger/dialog/CreateTriggerDialog.java
com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/trigger/editor/TriggerDashboardEditorPart.java
com.cubrid.cubridmanager.core.testfragment/src/com/cubrid/cubridmanager/core/cubrid/trigger/model/TriggerDDLTest.java
com.cubrid.cubridmanager.core.testfragment/src/com/cubrid/cubridmanager/core/cubrid/trigger/model/TriggerTest.java
com.cubrid.cubridmanager.core.testfragment/src/com/cubrid/cubridmanager/core/cubrid/trigger/task/GetTriggerInfoTaskTest.java
com.cubrid.cubridmanager.core.testfragment/src/com/cubrid/cubridmanager/core/cubrid/trigger/task/test.message/gettriggerinfo_receive
com.cubrid.cubridmanager.core.testfragment/src/com/cubrid/cubridmanager/core/messageSendReceiveTest.txt
com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/cubrid/trigger/model/TriggerDDL.java
com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/cubrid/trigger/task/JDBCGetTriggerInfoTask.java
com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/cubrid/trigger/task/JDBCGetTriggerListTask.java

- 사유
기존 변수명과 함수명을 CamelCase 형태로 변환
target_class, target_attribute 및 연관 함수

**Comment by hornetmj** [comment]
#31 
같은 이슈로 종료하겠습니다.
