### ISSUE TITLE
Refered 오타 수정

### ISSUE THREAD

**Issue by larvinion** [kosslab-kr/cubrid-manager#51]
아래 경로에 정의된 Refered를 Referred로 수정

- 경로
com.cubrid.common.ui/src/com/cubrid/common/ui/er/model/CubridTableParser.java
com.cubrid.common.ui/src/com/cubrid/common/ui/er/model/ERTable.java

- 사유
오타

**Comment by hornetmj** [comment]
수고하셨습니다. ^^
