### ISSUE TITLE
CM Convert to CamelCase

### ISSUE THREAD

**Issue by larvinion** [kosslab-kr/cubrid-manager#53]
Cubrid Manager 내 기존 코드를 CamelCase 형태로 변환

- 경로
com.cubrid.common.ui/src/com/cubrid/common/ui/query/editor/QueryEditorUtil.java
com.cubrid.cubridmanager.core.testfragment/src/com/cubrid/cubridmanager/core/broker/model/ApplyServerInfoTest.java
com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/broker/model/ApplyServerInfo.java
com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/cubrid/service/model/BrokerNode.java
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/broker/editor/ApplyServerLabelProvider.java
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/broker/editor/BrokerStatusView.java
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/database/editor/DatabaseDashboardEditor.java
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/mondashboard/editor/BrokerDashboardViewPart.java
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/mondashboard/editor/model/BrokerDBListNode.java
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/mondashboard/editor/model/ClientNode.java
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/mondashboard/editor/model/DashboardConnectionManager.java

- 사유
기존 변수명과 함수명을 CamelCase 형태로 변환

**Comment by larvinion** [comment]
@hornetmj 
변수명과 함수명 앞의 as 접두사가 ApplyServer를 뜻하는 것 같습니다.
객체를 생성하는 부분에서 객체명 앞에 as 란 접두사를 이미 쓰고 있는데,
ApplyServer를 뜻하는 as접두사가 변수명과 함수명에 쓰일 필요가 없어 보입니다.
이 부분에 대해서 어떻게 생각하시나요?

**Comment by hornetmj** [comment]
@larvinion 좋은 의견 감사드립니다. 해당 사항은 보기에 따라서 불필요해 보일 수도 있지만 아닐 수도 있습니다. 해당 사항은 우선 수정없이 진행하는 것으로 하면 좋을 것 같습니다.

**Comment by hornetmj** [comment]
merge 되었습니다. 검토 후 종료해주세요. 위에서 의견 주신거에 대한 추가 의견 있으시면 남겨주셔도 좋습니다.
