### ISSUE TITLE
DBA 확인 창 수정

### ISSUE THREAD

**Issue by hornetmj** [kosslab-kr/cubrid-manager#58]
데이터베이스 삭제 시 "DBA 확인" 창을 수정

- 재현
  - CUBRID 및 CM 구동
  - CUBRID Manager Server 연결
    - 왼쪽 "호스트" 창에서 "localhost" 더블 클릭 후 진행
      - CM과 CUBRID가 다른 호스트에 구동되어 있을 경우 "호스트 추가" 후 진행
  - 데이터베이스 구동 정지
    - demodb가 구동되어 있을 경우 "호스트" 창에서 확인 가능
      - DB가 구동되어 있지 않을 경우 구동 후 다시
    - demodb "우클릭" --> "데이터베이스 관리" --> "데이터베이스 삭제" --> "확인"
  - "DBA 확인" 창 팝업
- 수정 요청 사항    
  - "DBA 확인" 팝업창에서
      - 패스워드 입력 창을 밑으로 내리기
      - 패스워드 입력 창 고정
        - 지금은 창을 늘이면 같이 커짐
      - DBA 확인, DBA 권한을 확인합니다. --> DBA 권한 확인
      - 창 타이틀
        - "DBA 확인" --> "DBA 권한 확인"
  - 기타 사용자 편의성 증진을 위한 이슈 담당자의 의견 반영

**Comment by hornetmj** [comment]
김가연 님이 진행 중 입니다.

**Comment by gayeonkim1559** [comment]
In the below code lines is original code. 

`protected Control createDialogArea(Composite parent) {
		parentComp = (Composite) super.createDialogArea(parent);
		Composite composite = new Composite(parentComp, SWT.NONE);

		final GridLayout glSourceDBComposite = new GridLayout();
		glSourceDBComposite.marginHeight = convertVerticalDLUsToPixels(IDialogConstants.VERTICAL_MARGIN);
		glSourceDBComposite.marginWidth = convertHorizontalDLUsToPixels(IDialogConstants.HORIZONTAL_MARGIN);
		glSourceDBComposite.verticalSpacing = convertVerticalDLUsToPixels(IDialogConstants.VERTICAL_SPACING);
		glSourceDBComposite.horizontalSpacing = convertHorizontalDLUsToPixels(IDialogConstants.HORIZONTAL_SPACING);
		glSourceDBComposite.numColumns = 2;
		composite.setLayout(glSourceDBComposite);
		composite.setLayoutData(new GridData(GridData.FILL_BOTH));

		createDirectoryList(composite);

		setTitle(Messages.titleDeleteDbConfirmDialog);
		setMessage(Messages.msgDeleteDbConfirmDialog);

		return parentComp;
`
In this code, I change glSourceDBComposite.numColumns from 2 to 1 for password-text to be located below the label.

And the original constrained shell size was too small. So I modify the shell size that is 500*300
`
protected void constrainShellSize() {
		super.constrainShellSize();
		getShell().setSize(500, 300);
		CommonUITool.centerShell(getShell());
		getShell().setText(Messages.titleDeleteDbConfirmDialog);
}
`

I add the last three lines to constain the password text size no matter how the user increase the shell size.
`private void createDirectoryList(Composite composite) {

		Label clabel1 = new Label(composite, SWT.SHADOW_IN);
		final GridData gdClabel1 = CommonUITool.createGridData(1, 1, -1, -1);
		clabel1.setLayoutData(gdClabel1);
		clabel1.setText(Messages.msgInputDbaPassword);
		text = new Text(composite, SWT.BORDER | SWT.PASSWORD);
		GridData passwordData = new GridData(SWT.BEGINNING, SWT.CENTER, false, false);
		passwordData.widthHint = 300;
		text.setLayoutData(passwordData);

	}`

**Comment by hornetmj** [comment]
수고하셨습니다. ^^
