### ISSUE TITLE
Method Duplicate and CamelCase Convert

### ISSUE THREAD

**Issue by larvinion** [kosslab-kr/cubrid-manager#61]
- 경로
com.cubrid.cubridmanager.core/src/com/cubrid/cubridmanager/core/cubrid/table/model/DBClasses.java
com.cubrid.cubridmanager.core.testfragment/src/com/cubrid/cubridmanager/core/cubrid/table/model/DBClassesTest.java
com.cubrid.cubridmanager.core.testfragment/src/com/cubrid/cubridmanager/core/cubrid/table/task/GetClassListTaskTest.java

- 사유
DBClasses 클래스 내 중복 Method 처리 및 CamelCase 변환
`public void setDbName(String dbname) {
		this.dbname = dbname;
	}`
`public void setDbname(String dbname) {
		this.dbname = dbname;
	}`

**Comment by hornetmj** [comment]
merge 되었습니다.

수고하셨습니다^^
