### ISSUE TITLE
Infomation 오타 수정

### ISSUE THREAD

**Issue by larvinion** [kosslab-kr/cubrid-manager#78]
- 경로
com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/user/Messages.java
com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/user/Messages.properties
com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/user/Messages_jp_JP.properties
com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/user/Messages_km_KH.properties
com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/user/Messages_ko_KR.properties
com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/user/Messages_tr_TR.properties
com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/user/Messages_zh_CN.properties
com.cubrid.common.ui/src/com/cubrid/common/ui/cubrid/user/action/EditUserAction.java
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/database/Messages.java
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/database/Messages.properties
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/database/Messages_jp_JP.properties
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/database/Messages_km_KH.properties
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/database/Messages_ko_KR.properties
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/database/Messages_tr_TR.properties
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/database/Messages_zh_CN.properties
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/database/dialog/DeleteDatabaseDialog.java
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/user/Messages.java
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/user/Messages.properties
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/user/Messages_jp_JP.properties
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/user/Messages_km_KH.properties
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/user/Messages_ko_KR.properties
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/user/Messages_tr_TR.properties
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/cubrid/user/Messages_zh_CN.properties
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/shard/Messages.java
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/shard/Messages.properties
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/shard/Messages_jp_JP.properties
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/shard/Messages_ko_KR.properties
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/shard/Messages_tr_TR.properties
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/shard/Messages_zh_CN.properties
com.cubrid.cubridmanager.ui/src/com/cubrid/cubridmanager/ui/shard/common/ShardBrokerPropertiesPanel.java
com.cubrid.cubridquery.ui/src/com/cubrid/cubridquery/ui/common/Messages.java
com.cubrid.cubridquery.ui/src/com/cubrid/cubridquery/ui/common/Messages.properties
com.cubrid.cubridquery.ui/src/com/cubrid/cubridquery/ui/common/Messages_ko_KR.properties
com.cubrid.cubridquery.ui/src/com/cubrid/cubridquery/ui/common/Messages_zh_CN.properties

- 사유
Infomation -> Information 의 오타 수정

**Comment by hornetmj** [comment]
수고하셨습니다.

**Comment by hornetmj** [comment]
merge 되었습니다. 종료합니다.
